# NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

# importing the numpy library

In [8]:
import numpy as np

# Creating the nd array

In [15]:
###using list
ls=np.array([[1,2,3]])
type(ls)

numpy.ndarray

In [16]:
###rank of a numpy array
ls.ndim

2

In [22]:
#####using zeros(zeros)
###using empty(random values)
###using arange(low to high number generate)
###using eye(diagonals all are 1)
zer_numpy_array=np.zeros((2,3))
empty_array=np.empty((2,3))

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [40]:
##datatype for nd arrays
arr=np.array([1.2,3.6,4.6,5.6],dtype='float32')

In [41]:
##typecasting in nd arrays
arr.astype('int32')

array([1, 3, 4, 5], dtype=int32)

In [55]:
##basic  indexing and slicing
arr=np.array([1,2,3,4,5,6])
arr_1=arr[1:4].copy()

In [56]:
arr_1[2]=32

In [57]:
print(arr)
print(arr_1)

[1 2 3 4 5 6]
[ 2  3 32]


In [54]:
print(arr_1)

[ 2 32 32]


In [65]:
###play with 3d arrays
arr_3d=np.array([   [[1,2,3],[4,5,6]] , [[7,8,9],[10,11,12]]  ,  [[7,8,9],[10,11,12]]   ])

In [66]:
arr_3d.shape

(3, 2, 3)

In [75]:
arr_3d[2][1][2]


12

In [85]:
a=np.array([[1,2,3],[4,5,6]])
a[:2,:2]

array([[1, 2],
       [4, 5]])

In [99]:
####boolean indexing
names=np.array(['bob','marie','angel','nitish','a','b','c'])
data=np.random.randn(7,4)

In [100]:
data[names!='bob',:]

array([[ 1.33399624, -0.99730116,  2.69368713, -0.25039584],
       [ 0.57336375, -1.61169237, -1.28663663,  0.52074986],
       [-0.4384892 , -0.10466772, -0.09002381, -1.57659882],
       [ 0.49057171,  1.05015012,  1.23967891, -0.33097864],
       [-1.62056868,  0.12069616, -1.25344246, -0.75910199],
       [ 0.25857108, -0.92790367, -0.07943001,  0.04856286]])

In [104]:
#####fancy indexing
data[:,[1,3,0]]

array([[ 0.0925564 , -0.03350362,  0.51609298],
       [-0.99730116, -0.25039584,  1.33399624],
       [-1.61169237,  0.52074986,  0.57336375],
       [-0.10466772, -1.57659882, -0.4384892 ],
       [ 1.05015012, -0.33097864,  0.49057171],
       [ 0.12069616, -0.75910199, -1.62056868],
       [-0.92790367,  0.04856286,  0.25857108]])

In [111]:
####transposing the array
arr=np.arange(15).reshape(5,3)
arr.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [115]:
arr=np.arange(15)
print(np.exp(arr))
a,b=np.modf(arr)

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04
 1.62754791e+05 4.42413392e+05 1.20260428e+06]


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]


(None, None)

In [ ]:
###it contais all mathematical function

In [121]:
#####argmin,argmax,cumsum(2d array),argsort
np.argmin([0,1,2,8,28])
np.argmax([25,26,27,28])
np.argsort([55,66,77,0])
np.sort([5,4,3,2,1])

array([1, 2, 3, 4, 5])

In [131]:
a=np.array([[1,2],[4,5]])
b=np.array([[3,4],[5,6]])

In [123]:
a.shape

(15,)

In [127]:
###linear algebra @,Transpose,dot,inverse,trace
np.linalg.inv(a)

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [135]:
np.matmul(a,b)
####np.dot

array([[13, 16],
       [37, 46]])

In [61]:
####pseudorandom number generation:-seed,shuffle,permutation,randint(low,high,size),randn(shape),normal

In [173]:
##np.random.seed(1)
np.random.permutation(10)
##np.random.choice(10)
np.random.randint(1,20,size=(3,4))

array([[13,  2, 10, 19],
       [ 2,  3, 13,  8],
       [ 3, 11,  1, 10]])

In [2]:
import numpy as np

In [11]:
###element wise operation on vector(a+b,a<b,(a<b)*a)
a=np.array([1,2,8])
b=np.array([4,5,6])
a.shape
b.shape

(3,)

# broad casting in numpy arrays

# broadcasting with scalar  to vector


In [12]:
a=np.array([1,2,3])
a+1

array([2, 3, 4])

In [13]:
a*2

array([2, 4, 6])

In [18]:
###multipication with scalar of 2d tensor
m=np.array([[1,2,3],[4,5,6]])
2*m

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [30]:
a[:,None,None].shape

(3, 1, 1)

(3, 1)

# Broadcasting with scalar to matrix

In [38]:
##multipication with scalar of 2d tensor
m=np.array([[1,2,3],[4,5,6]])
2*m

array([[ 2,  4,  6],
       [ 8, 10, 12]])

# broadcasting with vector to matrix

In [40]:
###2d tensor + 1d tensor 
a=np.array([[1,2,3],[4,5,6]])
b=np.array([1,2,4])

In [41]:
a+b

array([[ 2,  4,  7],
       [ 5,  7, 10]])

In [53]:
##2d tensor + 2d tensor(changing dimension) 
a=np.array([[1,2,3]])
b=np.array([[6,7,8],[9,10,11],[12,13,14]])

In [54]:
np.broadcast_to(a,b.shape)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
##expanding axis(none or np.expand_dims)

In [46]:
np.broadcast_to(b,a.shape)

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (3,3) and requested shape (2,3)

# Broadcasting rules
When operating on two arrays, Numpy/PyTorch compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when

they are equal, or
one of them is 1



Arrays do not need to have the same number of dimensions. For example, if you have a 256* 256 *3 array of RGB values, and you want to scale each color in the image by a different value, you can multiply the image by a one-dimensional array with 3 values. Lining up the sizes of the trailing axes of these arrays according to the broadcast rules, shows that they are compatible:

Image  (3d array): 256 x 256 x 3
Scale  (1d array):             3
Result (3d array): 256 x 256 x 3
The numpy documentation includes several examples of what dimensions can and can not be broadcast together.

In [2]:
import numpy as np

# Matrix Multipication

In [3]:
m=np.array([[1,2,3],[4,5,6],[7,8,9]])
n=np.array([12,13,14])

In [4]:
###matrix vector product
np.dot(m,n)

array([ 80, 197, 314])

# matrixmultipication.xyz
http://matrixmultiplication.xyz/